# 빅데이터 개론 복습 2
> 파일 3-1 ~ 3-3

> 파이썬 숫자, 문자열, 행렬

- toc: true
- branch: master
- badges: true
- comments: true
- author: 김혜지
- categories: [python]

## 3-1 숫자

In [1]:
import math
import sys

In [2]:
type(8)

int

In [3]:
type(8.0)

float

In [4]:
x = 1 
y = 3 

x/y

In [6]:
type(x/y)

float

 소수점 17 자리 이상의 아주 작은 실수는 정확하게 숫자의 값을 저장하지 못한다.

In [7]:
1/3 + 0.0000000000000001  # 소수점 16자리 부동소수점

0.3333333333333334

In [9]:
1/3 == (1/3 + 0.0000000000000001) # 소수점 17자리 부동소수점

False

In [12]:
1/3 == (1/3 + 0.00000000000000001) #소수점 17개 이상은 컴퓨터에서 받아주지 못하는 모습

True

In [13]:
0.55 - 0.54

0.010000000000000009

두 수의 차이 값이 우리가 생각하는 결과와 다를 수 있다.

In [14]:
0.55 - 0.54 == 0.01

False

파이썬이 대수적으로 구별할 수 있는 가장 작은 수는 2.220446049250313e-16 이다. 

엡실론(Machine epsilon)이라고 부르며 파이썬의 계산 엡실론은 sys.float_info.epsilon 으로 알 수 있다.

In [15]:
machine_epsilon = sys.float_info.epsilon
machine_epsilon

2.220446049250313e-16

파이썬에서 큰 수를 출력해주는 경우 과학적 표기법(scientific notation)을 사용한다. 아래 식에서 2.0e+306는  2.0×10306  을 의미한다. 큰 수  2.0×10308  은 파이썬의 부동소수점 형식으로 저장할 수 없기 때문에 결과를 inf 로 나타낸다.

In [19]:
2.0e+306 #2.0×10의306제곱

2e+306

In [21]:
2.0e306 * 100

inf

## 3-2 문자열 

In [22]:
name_3 = "이철수"
name_3[0]

'이'

In [23]:
name_3[1:3]

'철수'

In [24]:
text_5 = 'There is a desk'
text_5

'There is a desk'

In [29]:
text_5.replace("is", "was") #문자열 따옴표 잊지 말기

'There was a desk'

In [30]:
text_5.upper() # 문자열을 모두 대문자로 

'THERE IS A DESK'

In [31]:
text_5.count('e') # 괄호안에 주어진 문자열이 몇 번 나타나는지 

3

In [32]:
text_5.split(sep=' ')  # sep= 으로 지정된 문자열을 사용하여 문자열을 나누어서 리스트로 저장

['There', 'is', 'a', 'desk']

## 실습

1. 본인의 단대, 학과, 학번, 이름(영문)을 각각 문자열로 정의하여라. 정의된 문자열을 하나로 결합하여라.

2. 위에서 정의된 본인의 이름을 모두 대문자로 바꾸어라.

3. 위에서 결합된 문자열에서 본인의 이름을 국문으로 바꾸어라.

4. 본인의 생년월일을 다음과 같은 형식으로 표기하는 문자열을 정의하여라. 1990/02/16

5. 생년월일에서 년에 해당하는 정보만을 추출하여라.

6. 생년월일을 년, 월, 일 새 부분으로 나누어라.

In [41]:
a = "인문대"
b = "스페인중남미학과"
c = "201821502"
d = "Hyeji"
aa = a +" "+ b +" "+ c +" "+ d
aa

'인문대 스페인중남미학과 201821502 Hyeji'

In [39]:
d.upper()

'HYEJI'

In [44]:
aa.replace(d, "혜지")

'인문대 스페인중남미학과 201821502 혜지'

In [47]:
e = "1000/02/01"

In [50]:
e[5:7]

'02'

In [53]:
e[0:4]

'1000'

In [55]:
e.split("/")

['1000', '02', '01']

In [60]:
## 다른 방법 -> "/" 단위로 자른 다음, 변수에 저장 후 년, 월, 일 출력 가능 

f1, f2, f3 = e.split(sep = "/")
f2

'02'

## 행렬(array)

이 과목에서는 행렬 형식보다 데이터프레임 형식의 자료를 주로 이용한다. 이 장에서는 라이브러리 numpy 에서 제공하는 행렬의 간단한 사용법만 살펴볼것이다.

In [62]:
import numpy as np

In [63]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

**행렬은 리스트와 달리 같은 형식의 자료만 모아 놓을 수 있다.**

In [65]:
np.array([1, 2, 'a']) #정의 안 됨 -> 같은 형식으로만 실행하기

array(['1', '2', 'a'], dtype='<U21')

In [66]:
a[0]

1

In [70]:
a[[0, 3, 5]] #행렬은 다음과 같이 순서의 위치를 []에 넣어서 부를 수 있음

array([1, 4, 6])

In [71]:
a[0:3]

array([1, 2, 3])

In [ ]:
#arrange

In [73]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [81]:
np.arange(2, 10, 2) #짝수 

array([2, 4, 6, 8])

In [82]:
np.arange(0, 10, 3) #0포함 3의 배수

array([0, 3, 6, 9])

In [83]:
np.arange(10, -10, -2)

array([10,  8,  6,  4,  2,  0, -2, -4, -6, -8])

2차원 행렬 - reshape()

In [84]:
b = np.arange(1, 9).reshape(2, 4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
b[0,0] #2차원에서 일부를 지정해 보는 법

1

In [94]:
b[0, 0:4] #1행, 1-4열 

array([1, 2, 3, 4])

In [96]:
b[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [95]:
c = b[0:2,1] #열이 하나밖에 없으므로 일차원 배열로 보여줌!!!!!!! 
c

array([2, 6])

In [97]:
c.ndim

1

In [103]:
c_1 = c.reshape(2,1) #2차원으로 바꾸기
c_1

array([[2],
       [6]])

In [99]:
d = b[1, 0:3]
d

array([5, 6, 7])

In [101]:
d.ndim

1

## 문제

다음과 같은 코드를 먼저 실행하고 물음에 답하여라

A = np.array([1, 4, 2, 5, 3])

1) A의 1, 3, 5 번째 원소를 추출하여라
2) A의 마지막 원소만 제외한 나머지로 이루어진 1차원 배열을 추출하여라
3) 5에서 1씩 감소하는 길이가 5인 1차원 배열을 만들고 B라 명명하여라
4) A와 B를 순서대로 연결하는 1차원 배열 C를 만들어라(concatenate([x,y])이용)
5) 위에서 만들어진 C로부터 A가 첫번째 행, B를 두번째 행이 되도록 2차원 배열(행렬) D를 정의 하여라 
6) D의 첫 두번째 행과 첫 두번째 열로 이루어진 부분행렬을 추출하여라
7) D의 세 번째 열로만 이루어진 배열을 추출하여라. 단, 1차원 배열이 아니라 2차원 배열의 속성을 그대로 가지도록 하여라


In [116]:
import numpy as np

In [117]:
A = np.array([1, 4, 2, 5, 3])

In [106]:
A[[0,2,4]] #1

array([1, 2, 3])

In [109]:
A[0:4]

array([1, 4, 2, 5])

In [114]:
#3
B = np.arange(5, 0, -1)
B

array([5, 4, 3, 2, 1])

In [121]:
#4

C = np.concatenate([A,B])
C

array([1, 4, 2, 5, 3, 5, 4, 3, 2, 1])

In [132]:
#5
D = C.reshape(2, 5) #2행 5열 인것을 잊지말기 행만 2개가 아닌 열도 신경써야함
D

array([[1, 4, 2, 5, 3],
       [5, 4, 3, 2, 1]])

In [134]:
#6
D[0:2, 0:2]

array([[1, 4],
       [5, 4]])

In [142]:
#7
D[:,2].reshape(2,1) #리솊을 해서 2차원으로 만들기

array([[2],
       [3]])